// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCShtPmSWPo2hKSnAw5Ei7Yn5B-AUhkBuQ',
    appId: '1:835531244883:web:5aaed3c6b0cf04271a0da6',
    messagingSenderId: '835531244883',
    projectId: 'soundapp-fb90e',
    authDomain: 'soundapp-fb90e.firebaseapp.com',
    storageBucket: 'soundapp-fb90e.appspot.com',
    measurementId: 'G-01E1GDL5ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqYncmjo1CGRKUkkcgYB7KTCrK5e-oPbE',
    appId: '1:835531244883:android:1735a07db2b062d21a0da6',
    messagingSenderId: '835531244883',
    projectId: 'soundapp-fb90e',
    storageBucket: 'soundapp-fb90e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4kddVIsaZpynZ6RTSg9ctOpY9QsqAIi4',
    appId: '1:835531244883:ios:b9dd2de548a57be31a0da6',
    messagingSenderId: '835531244883',
    projectId: 'soundapp-fb90e',
    storageBucket: 'soundapp-fb90e.appspot.com',
    iosBundleId: 'com.sound.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4kddVIsaZpynZ6RTSg9ctOpY9QsqAIi4',
    appId: '1:835531244883:ios:b9dd2de548a57be31a0da6',
    messagingSenderId: '835531244883',
    projectId: 'soundapp-fb90e',
    storageBucket: 'soundapp-fb90e.appspot.com',
    iosBundleId: 'com.sound.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCShtPmSWPo2hKSnAw5Ei7Yn5B-AUhkBuQ',
    appId: '1:835531244883:web:aa2c93fa961ef33c1a0da6',
    messagingSenderId: '835531244883',
    projectId: 'soundapp-fb90e',
    authDomain: 'soundapp-fb90e.firebaseapp.com',
    storageBucket: 'soundapp-fb90e.appspot.com',
    measurementId: 'G-MVW81JP0RR',
  );
}
